# Generated by Django 5.2.6 on 2025-12-01 14:37

import django.core.validators
import django.db.models.deletion
import dottify.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5), django.core.validators.StepValueValidator(0.5)])),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=800)),
                ('cover_img', models.ImageField(default='no_cover.jpg', upload_to='')),
                ('artist_name', models.CharField(max_length=800)),
                ('release_date', models.DateTimeField(validators=[django.core.validators.MaxValueValidator(dottify.models.Album.get_release_date)])),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MaxValueValidator(999.99), django.core.validators.MinValueValidator(0)])),
                ('format', models.CharField(choices=[('SNGL', 'Single'), ('RMST', 'Remaster'), ('DLUX', 'Deluxe Edition'), ('COMP', 'Compilation'), ('LIVE', 'Live Perfomance')], max_length=800)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(models.F('title'), models.F('artist_name'), name='unique_list_within_title')],
            },
        ),
        migrations.CreateModel(
            name='DottifyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=800)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=800)),
                ('length', models.IntegerField(validators=[django.core.validators.MinValueValidator(10)])),
                ('position', models.IntegerField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dottify.album')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=800)),
                ('visibility', models.IntegerField(choices=[(0, 'Hidden'), (1, 'Unlisted'), (2, 'Public')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dottify.dottifyuser')),
                ('songs', models.ManyToManyField(to='dottify.song')),
            ],
        ),
        migrations.AddConstraint(
            model_name='song',
            constraint=models.UniqueConstraint(models.F('title'), models.F('album'), name='unique_song_for_al'),
        ),
    ]
