# Generated by Django 5.2.6 on 2025-12-01 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dottify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='artist_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dottify.dottifyuser'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='visibility',
            field=models.IntegerField(choices=[(0, 'Hidden'), (1, 'Unlisted'), (2, 'Public')], default='0'),
        ),
        migrations.AlterField(
            model_name='song',
            name='position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
