# Generated by Django 5.2.6 on 2025-12-01 16:19

import django.core.validators
import dottify.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dottify', '0002_album_artist_account_alter_playlist_visibility_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(dottify.models.Album.get_release_date)]),
        ),
    ]
