# Generated by Django 5.2.6 on 2025-12-10 13:34

import django.db.models.deletion
import dottify.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dottify', '0003_alter_album_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commenttee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dottify.dottifyuser'),
        ),
        migrations.AddField(
            model_name='comment',
            name='song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dottify.song'),
        ),
        migrations.AddField(
            model_name='rating',
            name='album',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dottify.album'),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(default=dottify.models.Album.get_release_date),
        ),
    ]
