# Generated by Django 5.2.6 on 2025-12-10 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dottify', '0004_comment_commenttee_comment_song_rating_album_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 12, 10, 14, 33, 11, 99854)),
        ),
    ]
